#!/usr/bin/env bash
set -uo pipefail

REPO_ROOT="${REPO_ROOT:-/home/ali/gem-baseline}"
RESULTS_DIR="${RESULTS_DIR:-/home/ali/gem-baseline/results/msmarco_gem_20260419}"
LOG_DIR="${LOG_DIR:-${RESULTS_DIR}/logs}"
INDEX_ROOT="${INDEX_ROOT:-/data1/ali/msmarco-gem-data/example_index}"
BINARY="${BINARY:-${REPO_ROOT}/hnswlib/build/example_vecset_search_gem}"

OMP_NUM_THREADS="${OMP_NUM_THREADS:-90}"
OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-90}"
OMP_DYNAMIC="${OMP_DYNAMIC:-FALSE}"
GEM_REBUILD="${GEM_REBUILD:-1}"
GEM_BUILD_THREADS="${GEM_BUILD_THREADS:-80}"
GEM_SEARCH_THREADS="${GEM_SEARCH_THREADS:-1}"
GEM_EF_INDEX="${GEM_EF_INDEX:-80}"
GEM_CLUSTER_DISTANCE_BLOCK_ROWS="${GEM_CLUSTER_DISTANCE_BLOCK_ROWS:-1024}"
GEM_INDEX_ROOT="${GEM_INDEX_ROOT:-${INDEX_ROOT}}"
GEM_RESULTS_DIR="${GEM_RESULTS_DIR:-${RESULTS_DIR}}"
GEM_DATASET="${GEM_DATASET:-msmarco}"
GEM_DATASET_NAME="${GEM_DATASET_NAME:-${GEM_DATASET}}"
GEM_DATASET_PATH="${GEM_DATASET_PATH:-}"
GEM_NUM_CLUSTER="${GEM_NUM_CLUSTER:-}"
GEM_NUM_GRAPH_CLUSTER="${GEM_NUM_GRAPH_CLUSTER:-}"
GEM_SKIP_SEARCH="${GEM_SKIP_SEARCH:-0}"
GEM_MSMARCO_DATASET_PATH="${GEM_MSMARCO_DATASET_PATH:-/data/ali/msmarco-gem-data/}"
GEM_APPLY_REPAIR_ON_BUILD="${GEM_APPLY_REPAIR_ON_BUILD:-0}"
GEM_APPLY_REPAIR_ON_LOAD="${GEM_APPLY_REPAIR_ON_LOAD:-0}"
GEM_CLUSTER_ENTRY_SEED="${GEM_CLUSTER_ENTRY_SEED:-123}"
GEM_SHORTCUT_MODE="${GEM_SHORTCUT_MODE:-none}"
GEM_SHORTCUT_EDGE_FILE="${GEM_SHORTCUT_EDGE_FILE:-}"
GEM_PAPER_SHORTCUT_TRAIN_QEMBS="${GEM_PAPER_SHORTCUT_TRAIN_QEMBS:-}"
GEM_PAPER_SHORTCUT_TRAIN_QRELS="${GEM_PAPER_SHORTCUT_TRAIN_QRELS:-}"
GEM_SHORTCUT_TOPF="${GEM_SHORTCUT_TOPF:-100}"
GEM_PAPER_SHORTCUT_EF_SEARCH="${GEM_PAPER_SHORTCUT_EF_SEARCH:-${GEM_SHORTCUT_TOPF}}"
GEM_EF_LIST="${GEM_EF_LIST:-}"
GEM_RERANK_LIST="${GEM_RERANK_LIST:-}"
GEM_NPROB="${GEM_NPROB:-4}"
GEM_NPROB_LIST="${GEM_NPROB_LIST:-}"
GEM_QUERY_LIMIT="${GEM_QUERY_LIMIT:-}"
INDEX_DIR="${INDEX_DIR:-${INDEX_ROOT}/msmarcoIndex40960_all_24_${GEM_EF_INDEX}}"

mkdir -p "${RESULTS_DIR}" "${LOG_DIR}" "${INDEX_ROOT}"

timestamp="$(date +%Y%m%d_%H%M%S)"
log_file="${LOG_DIR}/gem_run_${timestamp}.log"
status_file="${LOG_DIR}/gem_run_${timestamp}.status"

echo "Logging to ${log_file}"
echo "Status file ${status_file}"

set +e
{
  echo "=== GEM MSMARCO Run ==="
  date --iso-8601=seconds
  echo "PWD=${REPO_ROOT}"
  echo "BINARY=${BINARY}"
  echo "RESULTS_DIR=${RESULTS_DIR}"
  echo "INDEX_DIR=${INDEX_DIR}"
  echo "OMP_NUM_THREADS=${OMP_NUM_THREADS}"
  echo "OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS}"
  echo "OMP_DYNAMIC=${OMP_DYNAMIC}"
  echo "GEM_REBUILD=${GEM_REBUILD}"
  echo "GEM_BUILD_THREADS=${GEM_BUILD_THREADS}"
  echo "GEM_SEARCH_THREADS=${GEM_SEARCH_THREADS}"
  echo "GEM_EF_INDEX=${GEM_EF_INDEX}"
  echo "GEM_CLUSTER_DISTANCE_BLOCK_ROWS=${GEM_CLUSTER_DISTANCE_BLOCK_ROWS}"
  echo "GEM_INDEX_ROOT=${GEM_INDEX_ROOT}"
  echo "GEM_RESULTS_DIR=${GEM_RESULTS_DIR}"
  echo "GEM_DATASET=${GEM_DATASET}"
  echo "GEM_DATASET_NAME=${GEM_DATASET_NAME}"
  echo "GEM_DATASET_PATH=${GEM_DATASET_PATH}"
  echo "GEM_NUM_CLUSTER=${GEM_NUM_CLUSTER}"
  echo "GEM_NUM_GRAPH_CLUSTER=${GEM_NUM_GRAPH_CLUSTER}"
  echo "GEM_SKIP_SEARCH=${GEM_SKIP_SEARCH}"
  echo "GEM_MSMARCO_DATASET_PATH=${GEM_MSMARCO_DATASET_PATH}"
  echo "GEM_APPLY_REPAIR_ON_BUILD=${GEM_APPLY_REPAIR_ON_BUILD}"
  echo "GEM_APPLY_REPAIR_ON_LOAD=${GEM_APPLY_REPAIR_ON_LOAD}"
  echo "GEM_CLUSTER_ENTRY_SEED=${GEM_CLUSTER_ENTRY_SEED}"
  echo "GEM_SHORTCUT_MODE=${GEM_SHORTCUT_MODE}"
  echo "GEM_SHORTCUT_EDGE_FILE=${GEM_SHORTCUT_EDGE_FILE}"
  echo "GEM_PAPER_SHORTCUT_TRAIN_QEMBS=${GEM_PAPER_SHORTCUT_TRAIN_QEMBS}"
  echo "GEM_PAPER_SHORTCUT_TRAIN_QRELS=${GEM_PAPER_SHORTCUT_TRAIN_QRELS}"
  echo "GEM_SHORTCUT_TOPF=${GEM_SHORTCUT_TOPF}"
  echo "GEM_PAPER_SHORTCUT_EF_SEARCH=${GEM_PAPER_SHORTCUT_EF_SEARCH}"
  echo "GEM_EF_LIST=${GEM_EF_LIST}"
  echo "GEM_RERANK_LIST=${GEM_RERANK_LIST}"
  echo "GEM_NPROB=${GEM_NPROB}"
  echo "GEM_NPROB_LIST=${GEM_NPROB_LIST}"
  echo "GEM_QUERY_LIMIT=${GEM_QUERY_LIMIT}"
  echo "======================="
  cd "${REPO_ROOT}"
  env \
    OMP_NUM_THREADS="${OMP_NUM_THREADS}" \
    OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS}" \
    OMP_DYNAMIC="${OMP_DYNAMIC}" \
    GEM_REBUILD="${GEM_REBUILD}" \
    GEM_BUILD_THREADS="${GEM_BUILD_THREADS}" \
    GEM_SEARCH_THREADS="${GEM_SEARCH_THREADS}" \
    GEM_EF_INDEX="${GEM_EF_INDEX}" \
    GEM_CLUSTER_DISTANCE_BLOCK_ROWS="${GEM_CLUSTER_DISTANCE_BLOCK_ROWS}" \
    GEM_INDEX_ROOT="${GEM_INDEX_ROOT}" \
    GEM_RESULTS_DIR="${GEM_RESULTS_DIR}" \
    GEM_DATASET="${GEM_DATASET}" \
    GEM_DATASET_NAME="${GEM_DATASET_NAME}" \
    GEM_DATASET_PATH="${GEM_DATASET_PATH}" \
    GEM_NUM_CLUSTER="${GEM_NUM_CLUSTER}" \
    GEM_NUM_GRAPH_CLUSTER="${GEM_NUM_GRAPH_CLUSTER}" \
    GEM_SKIP_SEARCH="${GEM_SKIP_SEARCH}" \
    GEM_MSMARCO_DATASET_PATH="${GEM_MSMARCO_DATASET_PATH}" \
    GEM_APPLY_REPAIR_ON_BUILD="${GEM_APPLY_REPAIR_ON_BUILD}" \
    GEM_APPLY_REPAIR_ON_LOAD="${GEM_APPLY_REPAIR_ON_LOAD}" \
    GEM_CLUSTER_ENTRY_SEED="${GEM_CLUSTER_ENTRY_SEED}" \
    GEM_SHORTCUT_MODE="${GEM_SHORTCUT_MODE}" \
    GEM_SHORTCUT_EDGE_FILE="${GEM_SHORTCUT_EDGE_FILE}" \
    GEM_PAPER_SHORTCUT_TRAIN_QEMBS="${GEM_PAPER_SHORTCUT_TRAIN_QEMBS}" \
    GEM_PAPER_SHORTCUT_TRAIN_QRELS="${GEM_PAPER_SHORTCUT_TRAIN_QRELS}" \
    GEM_SHORTCUT_TOPF="${GEM_SHORTCUT_TOPF}" \
    GEM_PAPER_SHORTCUT_EF_SEARCH="${GEM_PAPER_SHORTCUT_EF_SEARCH}" \
    GEM_EF_LIST="${GEM_EF_LIST}" \
    GEM_RERANK_LIST="${GEM_RERANK_LIST}" \
    GEM_NPROB="${GEM_NPROB}" \
    GEM_NPROB_LIST="${GEM_NPROB_LIST}" \
    GEM_QUERY_LIMIT="${GEM_QUERY_LIMIT}" \
    stdbuf -oL -eL "${BINARY}"
} 2>&1 | tee "${log_file}"
exit_code=${PIPESTATUS[0]}
set -e

{
  echo "EXIT_CODE=${exit_code}"
  date --iso-8601=seconds
} | tee -a "${log_file}" > "${status_file}"

if [[ "${KEEP_SHELL_ON_EXIT:-1}" == "1" ]]; then
  exec bash
fi

exit "${exit_code}"
